### ISSUE TITLE
Bulk Load CSV data into Postgres?

### ISSUE THREAD

**Issue by nk-cmd** [MarkPflug/Sylvan#228]
Hello Mark,

thanks for this library!

I tested your library and I have some trouble. I checked the documentation and Issues, but I didn't find any relevand information for me.

My scenario is, I read an .xlsx or .csv and must create this an database table.

Version:
```
<TargetFramework>net8.0</TargetFramework>
```
```
<PackageReference Include="Sylvan.Data.Csv" Version="1.3.5" />
<PackageReference Include="Sylvan.Data.Excel" Version="0.4.19" />
<PackageReference Include="Sylvan.Common" Version="0.4.3" />
```

With your example: (https://github.com/MarkPflug/Sylvan/blob/main/docs/Csv/Examples.md#bulk-load-csv-data-into-sqlserver)

```
// Get the schema for the target table
var cmd = conn.CreateCommand();
cmd.CommandText = "select top 0 * from MyDataSet";
var reader = cmd.ExecuteReader();
var tableSchema = reader.GetColumnSchema();

var options = 
    new CsvDataReaderOptions { 
        Schema = new CsvSchema(tableSchema)
    };

using var csv = CsvDataReader.Create("demo.csv", options);

var bcp = new SqlBulkCopy(conn);
bcp.BulkCopyTimeout = 0;
bcp.DestinationTableName = "MyDataSet";
bcp.BatchSize = 10000;
bcp.WriteToServer(csv);
```

Is that possible with postgres?

My coding looks like:

```
var conn = (NpgsqlConnection)context.Database.GetDbConnection();
await conn.OpenAsync();
var cmd = conn.CreateCommand();
cmd.CommandText = $"select * from dbo.\"{tableName}\"";
var sqlreader = cmd.ExecuteReader();

var sqltableSchema = sqlreader.GetColumnSchema();
var schemaTable = sqlreader.GetSchemaTable();

await conn.CloseAsync();
var dbColumns = sqltableSchema.Select(el => (DbColumn)el).ToList();


 using var reader = new StreamReader(path);
 if (reader.BaseStream.CanSeek) { reader.BaseStream.Seek(0, SeekOrigin.Begin); }

 var csvReadOpt = new CsvDataReaderOptions
 {
     Schema = new CsvSchema(dbColumns)
 };

 var txtReader = new StreamReader(reader.BaseStream);
 using var edr = await CsvDataReader.CreateAsync(txtReader, csvReadOpt);
 var tableSchema = edr.GetSchemaTable();

 conn = (NpgsqlConnection)context.Database.GetDbConnection();
 await conn.OpenAsync();
 using (var adapter = new NpgsqlDataAdapter())
 {
     adapter.InsertCommand = commandBuilder.GetInsertCommand();
     adapter.Update(tableSchema);
 }

```

I got following Exception 
```
System.InvalidOperationException: Missing the DataColumn 'A' in the DataTable 'SchemaTable' for the SourceColumn 'A'.
   at System.Data.Common.DbDataAdapter.UpdatingRowStatusErrors(RowUpdatingEventArgs rowUpdatedEvent, DataRow dataRow)
   at System.Data.Common.DbDataAdapter.Update(DataRow[] dataRows, DataTableMapping tableMapping)
   at System.Data.Common.DbDataAdapter.UpdateFromDataTable(DataTable dataTable, DataTableMapping tableMapping)
   at System.Data.Common.DbDataAdapter.Update(DataTable dataTable)
```

schemaTable.Columns
![image](https://github.com/MarkPflug/Sylvan/assets/62747555/2bfeaabd-91a0-4a04-8fdf-eea5b06f2a7a)

schemaTable.Rows
![image](https://github.com/MarkPflug/Sylvan/assets/62747555/9bcd8571-cedc-4fd6-830d-bbb07b67b83c)

I thought, that schemaTable.Rows contains the rows from the source.

Should I write my own schema provider?

Thanks,
nk

**Comment by MarkPflug** [comment]
Here is a complete example (tested on my machine), that shows how to use the same technique with postgres:
https://gist.github.com/MarkPflug/2c3c4fc39b1716788fd18093d64ab9da

This uses the `NpgsqlBinaryImporter` which is roughly equivalent to the `SqlBulkCopy ` type. Depending on the type of data that you're processing you might need to adjust some of the type mapping code.
