### ISSUE TITLE
DataTable.Load fails if file ends with multiple emtpy rows

### ISSUE THREAD

**Issue by stevenmccormack** [MarkPflug/Sylvan#98]
When using a TypedCsvSchema to load a CSV file directly into a DataTable an exception is thrown when the CSV end with multiple empty lines.

**TypedCsvColumn.cs**
```cs
class TypedCsvColumn : DbColumn {
        public TypedCsvColumn(Type type, bool allowNull,string name) {
            DataType = type;
            AllowDBNull = allowNull;
            ColumnName = name;
        }
    }
```

**TypedCsvSchema.cs**
```cs
class TypedCsvSchema : ICsvSchemaProvider {
        List<TypedCsvColumn> columns;

        public TypedCsvSchema() {
            columns = new List<TypedCsvColumn>();
        }

        public TypedCsvSchema Add(Type type, bool isNullable, string name) {
            columns.Add(new TypedCsvColumn(type, isNullable, name));
            return this;
        }

        public TypedCsvSchema Add<T>(string name, bool isNullable = false) {
            var  type      = typeof(T);
            bool allowNull = isNullable;
            var  baseType  = Nullable.GetUnderlyingType(type);
            if (baseType != null) {
                type      = baseType;
                allowNull = true;
            }

            return Add(type, allowNull, name);
        }

        DbColumn? ICsvSchemaProvider.GetColumn(string? name, int ordinal) {
            return ordinal < columns.Count ? columns[ordinal] : null;
        }
    }
```
**test method body**
```cs
var data = new DataTable();

var schema = new TypedCsvSchema()
    .Add<int>("id")
    .Add<string>("firstname")
    .Add<string>("lastname") ;

var options = new CsvDataReaderOptions {
    Schema = schema
};

await using (var csv = await CsvDataReader.CreateAsync("/tmp/testfile.csv",options)) {
    data.Load(csv);
}
```
This generates an exception as the empty line cannot be parsed.

```
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(ReadOnlySpan`1 s, NumberStyles style, IFormatProvider provider)
   at Sylvan.Data.Csv.CsvDataReader.GetInt32(Int32 ordinal)
   at Sylvan.Data.Csv.Int32Accessor.GetValue(CsvDataReader reader, Int32 ordinal)
   at Sylvan.Data.Csv.FieldAccessor`1.GetValueAsObject(CsvDataReader reader, Int32 ordinal)
   at Sylvan.Data.Csv.CsvDataReader.GetValue(Int32 ordinal)
   at Sylvan.Data.Csv.CsvDataReader.GetValues(Object[] values)
   at System.Data.ProviderBase.DataReaderContainer.CommonLanguageSubsetDataReader.GetValues(Object[] values)
   at System.Data.ProviderBase.SchemaMapping.LoadDataRow()
   at System.Data.Common.DataAdapter.FillLoadDataRow(SchemaMapping mapping)
   at System.Data.Common.DataAdapter.FillFromReader(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 startRecord, Int32 maxRecords, DataColumn parentChapterColumn, Object parentChapterValue)
   at System.Data.Common.DataAdapter.Fill(DataTable[] dataTables, IDataReader dataReader, Int32 startRecord, Int32 maxRecords)
   at System.Data.DataTable.Load(IDataReader reader, LoadOption loadOption, FillErrorEventHandler errorHandler)
   at System.Data.DataTable.Load(IDataReader reader)
```

When reading in a while loop with ReadAsync this can be prevented by checking if RowFieldCount = FieldCount.
Is there a way to tell the reader to skip empty rows when used by DataTable.Load()?

**Comment by MarkPflug** [comment]
Try setting `CsvDataReaderOptions.ResultSetMode = ResultSetMode.MultiResult`. If your file is otherwise well-formed (rectangular), it should have the effect of skipping any empty lines at the end of the file.

**Comment by stevenmccormack** [comment]
Thanks for the quick reply. Using this setting it works

**Comment by MarkPflug** [comment]
⭐
